### PR TITLE
[WIP] Feature/better linesearch

### PR DESCRIPTION
**Pull request by dfridovi**
Building a better Armijo-style line search into the core `ILQSolver`. The idea here is to ensure that image
 (the concatenated gradients of the costs for all players) is going down enough at each iteration. Specifically, we expect image to hold, again where we've concatenated all players' cost gradients and Hessians.

I know that this PR is *huge*. However, most of the changes are either (a) due to the `feature/min_over_time` branch which has yet to be fully merged with `master` (and can essentially be ignored) or (b) due to a Newton solver implementation, which has been aborted for now. Real changes (aside from refactors and the above) begin with 2345dc2be2c782c2b43974b2a2c3d8853dbe17e9.

Other notes:
- This implementation of the Armijo check is based on the partial derivatives in control _and_ state, not just on control. It does not seem to adversely affect things, however, using just control may make more sense.
- It may make more sense to use the partial derivatives in controller parameters, not control or state. Further thought on these issues is certainly warranted, but for now the search seems to be ok.

### CODE REVIEW

**Comment by dfridovi** [comment]
TODOs:
1. Finish writing core Armijo condition check, which can be sped up by checking sequentially in time and optionally failing early.
2. Factor out parts of `CurrentOperatingPoint` that can be easily modularized.

**Comment by dfridovi** [comment]
Just did (2) above.

**Comment by 4estlaine** [comment]
What are you defining as the KKT conditions for each player, specifically how do you define the gradient w.r.t. the state variables?

**Comment by dfridovi** [comment]
So I'm not sure if this is right, but I was planning to basically just treat it as an unconstrained problem where the decision variables are the `u`s for each player. The thought was that the dynamic constraints and the feedback constraints are effectively handled already by the LQ solver. I'm not sure if this is going to work, because for example just in the LQ case we know the unique feedback Nash trajectory will not satisfy the open loop KKT conditions like this... but it should be easy to try at least... I think to handle the feedback constraints properly the thing to do is to treat the strategies themselves (the Ks) as the primal variables and the KKT conditions as d cost / d K_t = 0 for all time/players. That, I think, we can actually compute already because it's just d cost / d u_t * d u_t / d K_t. This neglects the impact of earlier Ks (which I think you're basically including with the recursive implicit function business), but I think it seems right. Maybe I'm wrong? Anyway, hopefully I can have the simpler check implemented soon and then we can talk more about this during the week?

**Comment by dfridovi** [comment]
Ok I've confirmed that the naive Armijo condition above seems to work. Obviously we should think about whether it should really be something else, but for now I'll probably just leave it and move on to try the augmented Lagrangian stuff after fixing a few minor code quality of life issues.

**Comment by 4estlaine** [comment]
I see. Yeah if you are only checking the gradient of the lagrangian w.r.t. the control variables goes to 0, then I think the line search should converge. What I have been finding though is that the step direction is non-zero even if the gradient of the lagrangian w.r.t. the control variables is 0, implying that the necessary conditions that we are actually looking for are not met. Because we are using a colocation method (treating state-variables as decision variables) we need to evaluate the gradient of the each player's lagrangian w.r.t. the state variables too. But the gradient of the lagrangians w.r.t. the state involves the gradient of the constraint that all other players will follow the sub-game policy, multiplied by a multiplier. This is why I was saying that in order to evaluate the necessary conditions,I have been having to actually solve the system again, to get the new feedback terms so I can evaluate the gradient of the lagrangian after the candidate step. 

Anyways, I'm looking forward to chatting more about this in person! Lots of weird/interesting things to talk about

**Comment by dfridovi** [comment]
So what I think I convinced myself of last night while trying to go to sleep is that the necessary conditions for feedback Nash are going to also satisfy the necessary conditions for open loop Nash (on both states and controls as you say). This is because at any feedback Nash for the LQ game the instantaneous constraints u = Kx are always satisfied already, even if the gradients on control and state are nonzero. Anyway things to think about for sure...

Also, btw, something interesting I was wondering is that your equality constrained LQ subproblem approach may end up being faster than the augmented Lagrangian approach since it may very well involve fewer outer loop iterations (no AL penalty to crank up). I guess we'll have to see, since I'm not sure I understand the complexity of the active set logic.

**Comment by 4estlaine** [comment]
I actually don't think that's true. Because in the feedback case there is an additional constraint present (constraining the control variables of other players) the resulting multipliers on the dynamic constraints are going to be different, which are in turn going to cause the control variables to be different. Even though at convergence the constraint u^{-i}=pi^i(x) is satisfied exactly, the gradient is non-zero w.r.t. x, therefore corrupting the other multipliers associated with the dynamic constraints.

In terms of convergence, in theory that should be correct. Actually in Dimitri Bertsekas's book there is a section which derives a second-order augmented lagrangian method, which ends up looking almost identical to the standard SQP/newton method but with a slightly modified hessian. IIRC the augmented lagrangian method attains a super-linear (but not second-order) convergence rate while newton-type methods which account for constraints explicitly attain a second-order convergence rate.

``

**Comment by dfridovi** [comment]
Done with quality of life improvements, at least for now. I think this is ready for review and merge.

**Comment by dfridovi** [comment]
Note on that last commit - I did check that the LQ strategies (pre-linesearch) are converging as the overall algorithm converges, at least for some cases. I haven't seen a case where that's false, but this seems to indicate that we _are_ finding descent directions in these cases.

**Comment by 4estlaine** [comment]
Sorry to keep harking on this but I want to try to understand this. I looked through your code and it seems that when you compute the KKT error, you are only checking whether the gradient of the cost is 0 w.r.t. the state and control variables, no? I don't see where the gradient of dynamics * dynamics multipliers shows up. Or if you don't need those, can you explain why not? 

I ran some examples in your repo and found that the alpha vectors do seem to get small at most time steps near the termination of the algorithm for the three-player-intersection examples. I was kind of surprised by this to be honest, so I ran some experiments on my end and tried to replicate a similar example. Interestingly, this lead me to some weird findings where whenever I include cost functions or constraints that don't explicitly involve the angle or velocity dimensions of unicycle-type models, the algorithm finds a fb nash no problem. Its only when I start to make some weirder cost functions like that player A requires player B's angle to be pi/2 at the end of the trajectory that I have trouble converging. I ran your dubins_origin example and found that there the alpha vecs are also not converging, both for open and closed loop variants. 

I started digging into the conjectural variation stuff, and I stumbled across a whole bunch of really cool references linking feedback nash to conjectural variations. I think there are maybe some computational benefits to thinking about the problem in that way, at least that is what I have been reading. I am excited to dig more and see what is going on there.

**Comment by dfridovi** [comment]
Dang that's weird.... I'm so confused why it would break with angles. Like maybe the nonlinearity is only affecting things then for some reason? 

In any case I'm definitely excited about the conjectural variations stuff. I think that could really work, though I worry about convergence.

**Pull request merged**
